name: CI

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Run on Ubuntu

    steps:
      - uses: actions/checkout@v3  # Checkout code from GitHub
      - name: Use Python 3.9  # Use specific Python version
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt  # Replace with your dependencies file
      - name: Run tests
        run: pytest tests/  # Run tests using pytest
